version: '3.7'
services:
  service1:
    container_name: service1
    build: ./service1
    image: python-service1:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    container_name: service2
    build: ./service2
    image: python-service2:latest
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    container_name: service3
    build: ./service3
    image: python-service3:latest
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    container_name: service4
    build: ./service4
    image: python-service4:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  db:
    container_name: mysql
    build: ./db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_DATABASE: prizegenerator
      MYSQL_ROOT_PASSWORD: kelvinrules