---
# tasks file for deathstar_manager
- name: Init a new swarm with default parameters
  become: true
  community.docker.docker_swarm:
    state: present
  register: swarm_info
- name: Print Swarm Info
  debug:
  msg: "{{ swarm_info }}"